### ISSUE TITLE
ReferenceError: internalBinding is not defined

### ISSUE THREAD

**Issue by dqgdqg** [mayswind/AriaNg#320]
When I run the command "gulp clean build" after "npm install":
```shell
root@localhost:~/AriaNg-1.0.0# gulp clean build
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/root/AriaNg-1.0.0/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/root/AriaNg-1.0.0/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/root/AriaNg-1.0.0/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
```
OS: Ubuntu 16.04 LTS
Node version: v11.2
Gulp version: CLI version 2.0.1; Local version 3.9.1
How to troubleshoot it ?

**Comment by mayswind** [comment]
If you have any questions about gulp, please visit https://github.com/gulpjs/gulp
