### ISSUE TITLE
Failed build due to moment-timezone

### ISSUE THREAD

**Issue by hexchain** [mayswind/AriaNg#47]
Build failed when executing `gulp build`:
```
[20:00:08] Using gulpfile /path/to/AriaNg/gulpfile.js
[20:00:08] Starting 'clean'...
[20:00:08] Starting 'build'...
[20:00:08] Starting 'lint'...
[20:00:08] Finished 'clean' after 159 ms
[20:00:08] Finished 'lint' after 176 ms
[20:00:08] Starting 'styles'...
[20:00:09] Starting 'scripts'...
[20:00:09] Starting 'views'...
[20:00:09] Finished 'views' after 206 ms
[20:00:09] Finished 'styles' after 327 ms
[20:00:09] Finished 'scripts' after 229 ms
[20:00:09] Starting 'html'...
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Error: File not found with singular glob: /path/to/AriaNg/bower_components/moment-timezone/builds/moment-timezone-with-data-2010-2020.min.js
    at DestroyableTransform.<anonymous> (/path/to/AriaNg/node_modules/gulp-useref/index.js:65:28)
    at emitOne (events.js:101:20)
    at DestroyableTransform.emit (events.js:191:7)
    at emitOne (events.js:101:20)
    at Through2.emit (events.js:191:7)
    at OrderedStreams.<anonymous> (/path/to/AriaNg/node_modules/gulp-useref/node_modules/glob-stream/index.js:140:20)
    at emitOne (events.js:96:13)
    at OrderedStreams.emit (events.js:191:7)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:191:7)
```

Seems that `moment-timezone#0.5.13` only has `moment-timezone-with-data-2012-2022.min.js` now.

Manually changing relevant script tag in `src/index.html` fixes the build.

**Comment by mayswind** [comment]
AriaNg depends moment-timezone 0.5.11, and this version has moment-timezone-with-data-2012-2022.min.js

**Comment by hexchain** [comment]
`0.5.13` is perfectly valid for `^0.5.11`. In order to be futureproof, could you please instead use the file without year limit in name (or update `moment-timezone`)?

**Comment by mayswind** [comment]
thanks, I set the moment-timezone to a fixed version.
