### ISSUE TITLE
Error when try to build

### ISSUE THREAD

**Issue by raelb** [mayswind/AriaNg#585]
Hi,
I'm on Windows 10 x64.

I get an error when I try to run `gulp clean build-bundle`

λ gulp clean build-bundle
ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (C:\Downloads\Utilities\Download Managers\Other\AriaNg-master\node_modules\natives\index.js:137:5)
    at require (C:\Downloads\Utilities\Download Managers\Other\AriaNg-master\node_modules\natives\index.js:110:12)
    at util.js:25:21
    at req_ (C:\Downloads\Utilities\Download Managers\Other\AriaNg-master\node_modules\natives\index.js:137:5)
    at require (C:\Downloads\Utilities\Download Managers\Other\AriaNg-master\node_modules\natives\index.js:110:12)
    at fs.js:42:21
    at req_ (C:\Downloads\Utilities\Download Managers\Other\AriaNg-master\node_modules\natives\index.js:137:5)
    at Object.req [as require] (C:\Downloads\Utilities\Download Managers\Other\AriaNg-master\node_modules\natives\index.js:54:10)
    at Object.<anonymous> (C:\Downloads\Utilities\Download Managers\Other\AriaNg-master\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:99)

I just installed the latest version of gulp, i.e. 4.0.2

**Comment by raelb** [comment]
I see this issue is answered over here:
https://stackoverflow.com/questions/54433794/gulp-internalbinding-is-not-defined

run
`npm install natives@1.1.6 --save-dev`
